#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Impresiones Digitales


# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: images/flaicon.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: fcolavecchia@gmail.com 
  facebook: flavio.colavecchia
  flickr: 
  github: fcolavecchia
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: rucacura
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://flavio.colavecchia.net 

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#
# markdown: GFM
# markdown: kramdown
# kramdown:
#   input: GFM
#   # math_engine: mathjax
#   syntax_highlighter: rouge
# # highlighter: rouge


# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-seo-tag

encoding: utf-8

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
#
# SEO stuff
#
title: Impresiones Digitales 

# A short description (e.g., A blog dedicated to reviewing cat gifs), used as part of the title tag like Ben's Awesome Site | A blog dedicated to reviewing cat gifs instead of Ben's Awesome Site | Long description about a blog dedicated to reviewing cat gifs that would be used when page.title is not defined.
tagline: My opinions about life, the universe and everthing

#- A longer description used for the description meta tag. Also used as fallback for pages that don't provide their own description, and also as part of the page's title tag if neither page.title nor site.tagline has been defined.
# Short bio or description (displayed in the header)
description: A written and visual record of my opinions about life, the universe and everthing
author: 
  picture: /images/flaicon.png
  twitter: rucacura 

twitter:
  username: rucacura 
  # creator: rucacura
  card: summary

social:
  name: Flavio Colavecchia
  links:
    - https://twitter.com/rucacura
    - https://www.instagram.com/flavio_bar/
    - https://www.linkedin.com/in/flavio-d-colavecchia
    - https://github.com/fcolavecchia
 